/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package adventofcode2018

import adventofcode2018.day9.play

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(play(459,7_132_000).max())
}
